trigger:
  branches:
    include:
      - master

pool:
  vmImage: "windows-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  azureServiceConnection: "azure-rm-surv-connection"
  bicepTemplateFile: "bicep/main.bicep"
  releaseTemplate: "release-template.yml"

stages:
- stage: CI
  displayName: CI
  jobs: 
  - job: build_and_publish_backend
    steps:
    - task: NuGetToolInstaller@1

    - task: CopyFiles@2
      displayName: "Copy bicep files to Staging Directory"
      inputs:
        sourceFolder: bicep/
        targetFolder: "$(Build.ArtifactStagingDirectory)/"

    - task: NuGetCommand@2
      inputs:
        restoreSolution: "$(solution)"

    - task: DotNetCoreCLI@2
      inputs:
        command: "build"
        projects: |
          **/*.sln
        arguments: "--configuration $(BuildConfiguration)"

    - task: DotNetCoreCLI@2
      displayName: Publish Image Processing Azure Function
      inputs:
        command: publish
        publishWebProjects: false
        projects: |
          **/Surveillance.Function.ImageProcessing.csproj
        arguments: "--no-build --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/"

    - task: DotNetCoreCLI@2
      displayName: Publish Persistence Azure Function
      inputs:
        command: publish
        publishWebProjects: false
        projects: |
          **/Surveillance.Function.Persistence.csproj
        arguments: "--no-build --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/"

    - task: DotNetCoreCLI@2
      displayName: Publish Notification Azure Function
      inputs:
        command: publish
        publishWebProjects: false
        projects: |
          **/Surveillance.Function.Notification.csproj
        arguments: "--no-build --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/"

    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact"

- stage: 'IaC'
  displayName: 'IaC'
  dependsOn: CI
  jobs:
  - job: Bicep_infrastructure_provisioning
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Downloading artifact'
      inputs:
        buildType: 'current'
        artifact: drop
        targetPath: '$(System.ArtifactsDirectory)'

    - task: AzureCLI@2
      displayName: 'Bicep infrastructure provisioning'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment group create --resource-group surveillance-auto --template-file $(bicepTemplateFile)

- stage: 'CD'
  displayName: 'CD'
  dependsOn: IaC
  jobs:
  - template: ${{ variables.releaseTemplate }}
    parameters:
      variableGroup: 'Development'
      environment: 'Development'
