parameters:
- name: variableGroup
  type: string

- name: environment
  type: string

jobs:
  - deployment: DeployFunction
    displayName: 'Deploy function'
    variables:
      - group: ${{ parameters.variableGroup }} # points to variable group in Azure DevOps
    environment: ${{ parameters.environment }} # points to environments in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Downloading artifact'
            inputs:
              buildType: 'current'
              artifact: drop
              targetPath: '$(System.ArtifactsDirectory)'
          - task: AzureFunctionApp@1
            displayName: 'Deploy image processing function'
            inputs:
              azureSubscription: azure-rm-surv-connection
              appType: functionAppWindows
              appName: surv-image-processing
              package: $(System.ArtifactsDirectory)/**/Surveillance.Function.ImageProcessing.zip 
              deployToSlotOrASE: true
              resourceGroupName: surveillance-auto
              slotName: staging
          - task: AzureFunctionApp@1
            displayName: 'Deploy persistence function'
            inputs:
              azureSubscription: azure-rm-surv-connection
              appType: functionAppWindows
              appName: surv-persistence
              package: $(System.ArtifactsDirectory)/**/Surveillance.Function.Persistence.zip 
              deployToSlotOrASE: true
              resourceGroupName: surveillance-auto
              slotName: staging
          - task: AzureFunctionApp@1
            displayName: 'Deploy notification function'
            inputs:
              azureSubscription: azure-rm-surv-connection
              appType: functionAppWindows
              appName: surv-notification
              package: $(System.ArtifactsDirectory)/**/Surveillance.Function.Notification.zip 
              deployToSlotOrASE: true
              resourceGroupName: surveillance-auto
              slotName: staging
          - task: AzureAppServiceManage@0
            displayName: 'Swap image processing function slot'
            inputs:
              azureSubscription: azure-rm-surv-connection
              WebAppName: surv-image-processing
              ResourceGroupName: surveillance-auto
              SourceSlot: staging
              SwapWithProduction: true
          - task: AzureAppServiceManage@0
            displayName: 'Swap persistence function slot'
            inputs:
              azureSubscription: azure-rm-surv-connection
              WebAppName: surv-persistence
              ResourceGroupName: surveillance-auto
              SourceSlot: staging
              SwapWithProduction: true
          - task: AzureAppServiceManage@0
            displayName: 'Swap notification function slot'
            inputs:
              azureSubscription: azure-rm-surv-connection
              WebAppName: surv-notification
              ResourceGroupName: surveillance-auto
              SourceSlot: staging
              SwapWithProduction: true
