parameters:
- name: variableGroup
  type: string

- name: environment
  type: string

jobs:
  - deployment: DeployFunction
    displayName: 'Deploy function'
    variables:
      - group: ${{ parameters.variableGroup }} # points to variable group in Azure DevOps
    environment: ${{ parameters.environment }} # points to environments in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Downloading artifact'
            inputs:
              buildType: 'current'
              artifact: drop
              targetPath: '$(Pipeline.Workspace)'
          - task: AzureFunctionApp@1 # Add this at the end of your file
            inputs:
              azureSubscription: azure-surveillance-connection
              appType: functionAppWindows
              appName: surveillance-image-processing
              package: $(System.ArtifactStagingDirectory)/**/Surveillance.Function.ImageProcessing.zip 
