parameters:
- name: variableGroup
  type: string

- name: environment
  type: string

jobs:
  - deployment: DeployFunction
    displayName: 'Deploy function'
    variables:
      - group: ${{ parameters.variableGroup }} # points to variable group in Azure DevOps
    environment: ${{ parameters.environment }} # points to environments in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Downloading artifact'
            inputs:
              buildType: 'current'
              artifact: drop
              targetPath: '$(System.ArtifactsDirectory)'
          - task: AzureFunctionApp@1
            displayName: 'Deploy image processing function'
            inputs:
              azureSubscription: azure-rm-surv-connection
              appType: functionAppWindows
              appName: surv-image-processing
              package: $(System.ArtifactsDirectory)/**/Surveillance.Function.ImageProcessing.zip 
          - task: AzureFunctionApp@1
            displayName: 'Deploy persistence function'
            inputs:
              azureSubscription: azure-rm-surv-connection
              appType: functionAppWindows
              appName: surv-persistence
              package: $(System.ArtifactsDirectory)/**/Surveillance.Function.Persistence.zip 
