trigger:
  branches:
    include:
      - master

pool:
  vmImage: "windows-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: "$(solution)"

  - task: DotNetCoreCLI@2
    inputs:
      command: "build"
      projects: |
        **/*.sln
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: Publish Azure Function
    inputs:
      command: publish
      publishWebProjects: false
      projects: |
        **/Surveillance.Function.ImageProcessing.csproj
      arguments: "--no-build --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/AzureFunctions/"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
